// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: master.proto

package si.mlimedija.proto;

public interface DeleteKeysRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Master.DeleteKeysRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 nodeId = 1;</code>
   */
  int getNodeId();

  /**
   * <code>string keys = 2;</code>
   */
  java.lang.String getKeys();
  /**
   * <code>string keys = 2;</code>
   */
  com.google.protobuf.ByteString
      getKeysBytes();
}
