// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: master.proto

package si.mlimedija.proto;

/**
 * <pre>
 * initial response for get file
 * </pre>
 *
 * Protobuf type {@code Master.GetFileEndpointResponse}
 */
public  final class GetFileEndpointResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Master.GetFileEndpointResponse)
    GetFileEndpointResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetFileEndpointResponse.newBuilder() to construct.
  private GetFileEndpointResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetFileEndpointResponse() {
    nodeIpAddress_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    isStoredOnS3_ = false;
    s3BucketName_ = "";
    s3ObjectKey_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetFileEndpointResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              nodeIpAddress_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            nodeIpAddress_.add(s);
            break;
          }
          case 16: {

            isStoredOnS3_ = input.readBool();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            s3BucketName_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            s3ObjectKey_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        nodeIpAddress_ = nodeIpAddress_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return si.mlimedija.proto.Master.internal_static_Master_GetFileEndpointResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return si.mlimedija.proto.Master.internal_static_Master_GetFileEndpointResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            si.mlimedija.proto.GetFileEndpointResponse.class, si.mlimedija.proto.GetFileEndpointResponse.Builder.class);
  }

  private int bitField0_;
  public static final int NODEIPADDRESS_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList nodeIpAddress_;
  /**
   * <code>repeated string nodeIpAddress = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getNodeIpAddressList() {
    return nodeIpAddress_;
  }
  /**
   * <code>repeated string nodeIpAddress = 1;</code>
   */
  public int getNodeIpAddressCount() {
    return nodeIpAddress_.size();
  }
  /**
   * <code>repeated string nodeIpAddress = 1;</code>
   */
  public java.lang.String getNodeIpAddress(int index) {
    return nodeIpAddress_.get(index);
  }
  /**
   * <code>repeated string nodeIpAddress = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNodeIpAddressBytes(int index) {
    return nodeIpAddress_.getByteString(index);
  }

  public static final int ISSTOREDONS3_FIELD_NUMBER = 2;
  private boolean isStoredOnS3_;
  /**
   * <code>bool isStoredOnS3 = 2;</code>
   */
  public boolean getIsStoredOnS3() {
    return isStoredOnS3_;
  }

  public static final int S3BUCKETNAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object s3BucketName_;
  /**
   * <code>string s3BucketName = 3;</code>
   */
  public java.lang.String getS3BucketName() {
    java.lang.Object ref = s3BucketName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      s3BucketName_ = s;
      return s;
    }
  }
  /**
   * <code>string s3BucketName = 3;</code>
   */
  public com.google.protobuf.ByteString
      getS3BucketNameBytes() {
    java.lang.Object ref = s3BucketName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      s3BucketName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int S3OBJECTKEY_FIELD_NUMBER = 4;
  private volatile java.lang.Object s3ObjectKey_;
  /**
   * <code>string s3ObjectKey = 4;</code>
   */
  public java.lang.String getS3ObjectKey() {
    java.lang.Object ref = s3ObjectKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      s3ObjectKey_ = s;
      return s;
    }
  }
  /**
   * <code>string s3ObjectKey = 4;</code>
   */
  public com.google.protobuf.ByteString
      getS3ObjectKeyBytes() {
    java.lang.Object ref = s3ObjectKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      s3ObjectKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < nodeIpAddress_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nodeIpAddress_.getRaw(i));
    }
    if (isStoredOnS3_ != false) {
      output.writeBool(2, isStoredOnS3_);
    }
    if (!getS3BucketNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, s3BucketName_);
    }
    if (!getS3ObjectKeyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, s3ObjectKey_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < nodeIpAddress_.size(); i++) {
        dataSize += computeStringSizeNoTag(nodeIpAddress_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getNodeIpAddressList().size();
    }
    if (isStoredOnS3_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, isStoredOnS3_);
    }
    if (!getS3BucketNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, s3BucketName_);
    }
    if (!getS3ObjectKeyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, s3ObjectKey_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof si.mlimedija.proto.GetFileEndpointResponse)) {
      return super.equals(obj);
    }
    si.mlimedija.proto.GetFileEndpointResponse other = (si.mlimedija.proto.GetFileEndpointResponse) obj;

    boolean result = true;
    result = result && getNodeIpAddressList()
        .equals(other.getNodeIpAddressList());
    result = result && (getIsStoredOnS3()
        == other.getIsStoredOnS3());
    result = result && getS3BucketName()
        .equals(other.getS3BucketName());
    result = result && getS3ObjectKey()
        .equals(other.getS3ObjectKey());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getNodeIpAddressCount() > 0) {
      hash = (37 * hash) + NODEIPADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getNodeIpAddressList().hashCode();
    }
    hash = (37 * hash) + ISSTOREDONS3_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsStoredOnS3());
    hash = (37 * hash) + S3BUCKETNAME_FIELD_NUMBER;
    hash = (53 * hash) + getS3BucketName().hashCode();
    hash = (37 * hash) + S3OBJECTKEY_FIELD_NUMBER;
    hash = (53 * hash) + getS3ObjectKey().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static si.mlimedija.proto.GetFileEndpointResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static si.mlimedija.proto.GetFileEndpointResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static si.mlimedija.proto.GetFileEndpointResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static si.mlimedija.proto.GetFileEndpointResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static si.mlimedija.proto.GetFileEndpointResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static si.mlimedija.proto.GetFileEndpointResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static si.mlimedija.proto.GetFileEndpointResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static si.mlimedija.proto.GetFileEndpointResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static si.mlimedija.proto.GetFileEndpointResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static si.mlimedija.proto.GetFileEndpointResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static si.mlimedija.proto.GetFileEndpointResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static si.mlimedija.proto.GetFileEndpointResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(si.mlimedija.proto.GetFileEndpointResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * initial response for get file
   * </pre>
   *
   * Protobuf type {@code Master.GetFileEndpointResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Master.GetFileEndpointResponse)
      si.mlimedija.proto.GetFileEndpointResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return si.mlimedija.proto.Master.internal_static_Master_GetFileEndpointResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return si.mlimedija.proto.Master.internal_static_Master_GetFileEndpointResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              si.mlimedija.proto.GetFileEndpointResponse.class, si.mlimedija.proto.GetFileEndpointResponse.Builder.class);
    }

    // Construct using si.mlimedija.proto.GetFileEndpointResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      nodeIpAddress_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      isStoredOnS3_ = false;

      s3BucketName_ = "";

      s3ObjectKey_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return si.mlimedija.proto.Master.internal_static_Master_GetFileEndpointResponse_descriptor;
    }

    @java.lang.Override
    public si.mlimedija.proto.GetFileEndpointResponse getDefaultInstanceForType() {
      return si.mlimedija.proto.GetFileEndpointResponse.getDefaultInstance();
    }

    @java.lang.Override
    public si.mlimedija.proto.GetFileEndpointResponse build() {
      si.mlimedija.proto.GetFileEndpointResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public si.mlimedija.proto.GetFileEndpointResponse buildPartial() {
      si.mlimedija.proto.GetFileEndpointResponse result = new si.mlimedija.proto.GetFileEndpointResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        nodeIpAddress_ = nodeIpAddress_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.nodeIpAddress_ = nodeIpAddress_;
      result.isStoredOnS3_ = isStoredOnS3_;
      result.s3BucketName_ = s3BucketName_;
      result.s3ObjectKey_ = s3ObjectKey_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof si.mlimedija.proto.GetFileEndpointResponse) {
        return mergeFrom((si.mlimedija.proto.GetFileEndpointResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(si.mlimedija.proto.GetFileEndpointResponse other) {
      if (other == si.mlimedija.proto.GetFileEndpointResponse.getDefaultInstance()) return this;
      if (!other.nodeIpAddress_.isEmpty()) {
        if (nodeIpAddress_.isEmpty()) {
          nodeIpAddress_ = other.nodeIpAddress_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureNodeIpAddressIsMutable();
          nodeIpAddress_.addAll(other.nodeIpAddress_);
        }
        onChanged();
      }
      if (other.getIsStoredOnS3() != false) {
        setIsStoredOnS3(other.getIsStoredOnS3());
      }
      if (!other.getS3BucketName().isEmpty()) {
        s3BucketName_ = other.s3BucketName_;
        onChanged();
      }
      if (!other.getS3ObjectKey().isEmpty()) {
        s3ObjectKey_ = other.s3ObjectKey_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      si.mlimedija.proto.GetFileEndpointResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (si.mlimedija.proto.GetFileEndpointResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList nodeIpAddress_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureNodeIpAddressIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        nodeIpAddress_ = new com.google.protobuf.LazyStringArrayList(nodeIpAddress_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string nodeIpAddress = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getNodeIpAddressList() {
      return nodeIpAddress_.getUnmodifiableView();
    }
    /**
     * <code>repeated string nodeIpAddress = 1;</code>
     */
    public int getNodeIpAddressCount() {
      return nodeIpAddress_.size();
    }
    /**
     * <code>repeated string nodeIpAddress = 1;</code>
     */
    public java.lang.String getNodeIpAddress(int index) {
      return nodeIpAddress_.get(index);
    }
    /**
     * <code>repeated string nodeIpAddress = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNodeIpAddressBytes(int index) {
      return nodeIpAddress_.getByteString(index);
    }
    /**
     * <code>repeated string nodeIpAddress = 1;</code>
     */
    public Builder setNodeIpAddress(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureNodeIpAddressIsMutable();
      nodeIpAddress_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string nodeIpAddress = 1;</code>
     */
    public Builder addNodeIpAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureNodeIpAddressIsMutable();
      nodeIpAddress_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string nodeIpAddress = 1;</code>
     */
    public Builder addAllNodeIpAddress(
        java.lang.Iterable<java.lang.String> values) {
      ensureNodeIpAddressIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, nodeIpAddress_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string nodeIpAddress = 1;</code>
     */
    public Builder clearNodeIpAddress() {
      nodeIpAddress_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string nodeIpAddress = 1;</code>
     */
    public Builder addNodeIpAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureNodeIpAddressIsMutable();
      nodeIpAddress_.add(value);
      onChanged();
      return this;
    }

    private boolean isStoredOnS3_ ;
    /**
     * <code>bool isStoredOnS3 = 2;</code>
     */
    public boolean getIsStoredOnS3() {
      return isStoredOnS3_;
    }
    /**
     * <code>bool isStoredOnS3 = 2;</code>
     */
    public Builder setIsStoredOnS3(boolean value) {
      
      isStoredOnS3_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool isStoredOnS3 = 2;</code>
     */
    public Builder clearIsStoredOnS3() {
      
      isStoredOnS3_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object s3BucketName_ = "";
    /**
     * <code>string s3BucketName = 3;</code>
     */
    public java.lang.String getS3BucketName() {
      java.lang.Object ref = s3BucketName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        s3BucketName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string s3BucketName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getS3BucketNameBytes() {
      java.lang.Object ref = s3BucketName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        s3BucketName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string s3BucketName = 3;</code>
     */
    public Builder setS3BucketName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      s3BucketName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string s3BucketName = 3;</code>
     */
    public Builder clearS3BucketName() {
      
      s3BucketName_ = getDefaultInstance().getS3BucketName();
      onChanged();
      return this;
    }
    /**
     * <code>string s3BucketName = 3;</code>
     */
    public Builder setS3BucketNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      s3BucketName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object s3ObjectKey_ = "";
    /**
     * <code>string s3ObjectKey = 4;</code>
     */
    public java.lang.String getS3ObjectKey() {
      java.lang.Object ref = s3ObjectKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        s3ObjectKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string s3ObjectKey = 4;</code>
     */
    public com.google.protobuf.ByteString
        getS3ObjectKeyBytes() {
      java.lang.Object ref = s3ObjectKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        s3ObjectKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string s3ObjectKey = 4;</code>
     */
    public Builder setS3ObjectKey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      s3ObjectKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string s3ObjectKey = 4;</code>
     */
    public Builder clearS3ObjectKey() {
      
      s3ObjectKey_ = getDefaultInstance().getS3ObjectKey();
      onChanged();
      return this;
    }
    /**
     * <code>string s3ObjectKey = 4;</code>
     */
    public Builder setS3ObjectKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      s3ObjectKey_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Master.GetFileEndpointResponse)
  }

  // @@protoc_insertion_point(class_scope:Master.GetFileEndpointResponse)
  private static final si.mlimedija.proto.GetFileEndpointResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new si.mlimedija.proto.GetFileEndpointResponse();
  }

  public static si.mlimedija.proto.GetFileEndpointResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetFileEndpointResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetFileEndpointResponse>() {
    @java.lang.Override
    public GetFileEndpointResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetFileEndpointResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetFileEndpointResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetFileEndpointResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public si.mlimedija.proto.GetFileEndpointResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

