// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: master.proto

package si.mlimedija.proto;

public interface GetFileEndpointResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Master.GetFileEndpointResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string nodeIpAddress = 1;</code>
   */
  java.util.List<java.lang.String>
      getNodeIpAddressList();
  /**
   * <code>repeated string nodeIpAddress = 1;</code>
   */
  int getNodeIpAddressCount();
  /**
   * <code>repeated string nodeIpAddress = 1;</code>
   */
  java.lang.String getNodeIpAddress(int index);
  /**
   * <code>repeated string nodeIpAddress = 1;</code>
   */
  com.google.protobuf.ByteString
      getNodeIpAddressBytes(int index);

  /**
   * <code>bool isStoredOnS3 = 2;</code>
   */
  boolean getIsStoredOnS3();

  /**
   * <code>string s3BucketName = 3;</code>
   */
  java.lang.String getS3BucketName();
  /**
   * <code>string s3BucketName = 3;</code>
   */
  com.google.protobuf.ByteString
      getS3BucketNameBytes();

  /**
   * <code>string s3ObjectKey = 4;</code>
   */
  java.lang.String getS3ObjectKey();
  /**
   * <code>string s3ObjectKey = 4;</code>
   */
  com.google.protobuf.ByteString
      getS3ObjectKeyBytes();
}
