// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NodeInfo.proto

package si.mlimedija.proto;

/**
 * <pre>
 * get storage node's info status =&gt; response
 * </pre>
 *
 * Protobuf type {@code NodeInfoResponse}
 */
public  final class NodeInfoResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:NodeInfoResponse)
    NodeInfoResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NodeInfoResponse.newBuilder() to construct.
  private NodeInfoResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NodeInfoResponse() {
    nodeId_ = 0;
    nodeIpAddress_ = "";
    isHealthy_ = false;
    mapSize_ = 0;
    responseCode_ = 0;
    responseMessage_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NodeInfoResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            nodeId_ = input.readInt32();
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            nodeIpAddress_ = s;
            break;
          }
          case 24: {

            isHealthy_ = input.readBool();
            break;
          }
          case 32: {

            mapSize_ = input.readInt32();
            break;
          }
          case 40: {

            responseCode_ = input.readInt32();
            break;
          }
          case 50: {
            String s = input.readStringRequireUtf8();

            responseMessage_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return NodeInfo.internal_static_NodeInfoResponse_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return NodeInfo.internal_static_NodeInfoResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            NodeInfoResponse.class, Builder.class);
  }

  public static final int NODEID_FIELD_NUMBER = 1;
  private int nodeId_;
  /**
   * <code>int32 nodeId = 1;</code>
   */
  public int getNodeId() {
    return nodeId_;
  }

  public static final int NODEIPADDRESS_FIELD_NUMBER = 2;
  private volatile Object nodeIpAddress_;
  /**
   * <code>string nodeIpAddress = 2;</code>
   */
  public String getNodeIpAddress() {
    Object ref = nodeIpAddress_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      nodeIpAddress_ = s;
      return s;
    }
  }
  /**
   * <code>string nodeIpAddress = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNodeIpAddressBytes() {
    Object ref = nodeIpAddress_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      nodeIpAddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISHEALTHY_FIELD_NUMBER = 3;
  private boolean isHealthy_;
  /**
   * <code>bool isHealthy = 3;</code>
   */
  public boolean getIsHealthy() {
    return isHealthy_;
  }

  public static final int MAPSIZE_FIELD_NUMBER = 4;
  private int mapSize_;
  /**
   * <code>int32 mapSize = 4;</code>
   */
  public int getMapSize() {
    return mapSize_;
  }

  public static final int RESPONSECODE_FIELD_NUMBER = 5;
  private int responseCode_;
  /**
   * <code>int32 responseCode = 5;</code>
   */
  public int getResponseCode() {
    return responseCode_;
  }

  public static final int RESPONSEMESSAGE_FIELD_NUMBER = 6;
  private volatile Object responseMessage_;
  /**
   * <code>string responseMessage = 6;</code>
   */
  public String getResponseMessage() {
    Object ref = responseMessage_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      responseMessage_ = s;
      return s;
    }
  }
  /**
   * <code>string responseMessage = 6;</code>
   */
  public com.google.protobuf.ByteString
      getResponseMessageBytes() {
    Object ref = responseMessage_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      responseMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (nodeId_ != 0) {
      output.writeInt32(1, nodeId_);
    }
    if (!getNodeIpAddressBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nodeIpAddress_);
    }
    if (isHealthy_ != false) {
      output.writeBool(3, isHealthy_);
    }
    if (mapSize_ != 0) {
      output.writeInt32(4, mapSize_);
    }
    if (responseCode_ != 0) {
      output.writeInt32(5, responseCode_);
    }
    if (!getResponseMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, responseMessage_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (nodeId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, nodeId_);
    }
    if (!getNodeIpAddressBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nodeIpAddress_);
    }
    if (isHealthy_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, isHealthy_);
    }
    if (mapSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, mapSize_);
    }
    if (responseCode_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, responseCode_);
    }
    if (!getResponseMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, responseMessage_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof NodeInfoResponse)) {
      return super.equals(obj);
    }
    NodeInfoResponse other = (NodeInfoResponse) obj;

    boolean result = true;
    result = result && (getNodeId()
        == other.getNodeId());
    result = result && getNodeIpAddress()
        .equals(other.getNodeIpAddress());
    result = result && (getIsHealthy()
        == other.getIsHealthy());
    result = result && (getMapSize()
        == other.getMapSize());
    result = result && (getResponseCode()
        == other.getResponseCode());
    result = result && getResponseMessage()
        .equals(other.getResponseMessage());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NODEID_FIELD_NUMBER;
    hash = (53 * hash) + getNodeId();
    hash = (37 * hash) + NODEIPADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getNodeIpAddress().hashCode();
    hash = (37 * hash) + ISHEALTHY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsHealthy());
    hash = (37 * hash) + MAPSIZE_FIELD_NUMBER;
    hash = (53 * hash) + getMapSize();
    hash = (37 * hash) + RESPONSECODE_FIELD_NUMBER;
    hash = (53 * hash) + getResponseCode();
    hash = (37 * hash) + RESPONSEMESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getResponseMessage().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static NodeInfoResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NodeInfoResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NodeInfoResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NodeInfoResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NodeInfoResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NodeInfoResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NodeInfoResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static NodeInfoResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static NodeInfoResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static NodeInfoResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static NodeInfoResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static NodeInfoResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(NodeInfoResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * get storage node's info status =&gt; response
   * </pre>
   *
   * Protobuf type {@code NodeInfoResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:NodeInfoResponse)
      NodeInfoResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NodeInfo.internal_static_NodeInfoResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NodeInfo.internal_static_NodeInfoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NodeInfoResponse.class, Builder.class);
    }

    // Construct using si.mlimedija.proto.NodeInfoResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      nodeId_ = 0;

      nodeIpAddress_ = "";

      isHealthy_ = false;

      mapSize_ = 0;

      responseCode_ = 0;

      responseMessage_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return NodeInfo.internal_static_NodeInfoResponse_descriptor;
    }

    @Override
    public NodeInfoResponse getDefaultInstanceForType() {
      return NodeInfoResponse.getDefaultInstance();
    }

    @Override
    public NodeInfoResponse build() {
      NodeInfoResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public NodeInfoResponse buildPartial() {
      NodeInfoResponse result = new NodeInfoResponse(this);
      result.nodeId_ = nodeId_;
      result.nodeIpAddress_ = nodeIpAddress_;
      result.isHealthy_ = isHealthy_;
      result.mapSize_ = mapSize_;
      result.responseCode_ = responseCode_;
      result.responseMessage_ = responseMessage_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof NodeInfoResponse) {
        return mergeFrom((NodeInfoResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(NodeInfoResponse other) {
      if (other == NodeInfoResponse.getDefaultInstance()) return this;
      if (other.getNodeId() != 0) {
        setNodeId(other.getNodeId());
      }
      if (!other.getNodeIpAddress().isEmpty()) {
        nodeIpAddress_ = other.nodeIpAddress_;
        onChanged();
      }
      if (other.getIsHealthy() != false) {
        setIsHealthy(other.getIsHealthy());
      }
      if (other.getMapSize() != 0) {
        setMapSize(other.getMapSize());
      }
      if (other.getResponseCode() != 0) {
        setResponseCode(other.getResponseCode());
      }
      if (!other.getResponseMessage().isEmpty()) {
        responseMessage_ = other.responseMessage_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      NodeInfoResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (NodeInfoResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int nodeId_ ;
    /**
     * <code>int32 nodeId = 1;</code>
     */
    public int getNodeId() {
      return nodeId_;
    }
    /**
     * <code>int32 nodeId = 1;</code>
     */
    public Builder setNodeId(int value) {
      
      nodeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 nodeId = 1;</code>
     */
    public Builder clearNodeId() {
      
      nodeId_ = 0;
      onChanged();
      return this;
    }

    private Object nodeIpAddress_ = "";
    /**
     * <code>string nodeIpAddress = 2;</code>
     */
    public String getNodeIpAddress() {
      Object ref = nodeIpAddress_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        nodeIpAddress_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string nodeIpAddress = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNodeIpAddressBytes() {
      Object ref = nodeIpAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        nodeIpAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string nodeIpAddress = 2;</code>
     */
    public Builder setNodeIpAddress(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nodeIpAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string nodeIpAddress = 2;</code>
     */
    public Builder clearNodeIpAddress() {
      
      nodeIpAddress_ = getDefaultInstance().getNodeIpAddress();
      onChanged();
      return this;
    }
    /**
     * <code>string nodeIpAddress = 2;</code>
     */
    public Builder setNodeIpAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nodeIpAddress_ = value;
      onChanged();
      return this;
    }

    private boolean isHealthy_ ;
    /**
     * <code>bool isHealthy = 3;</code>
     */
    public boolean getIsHealthy() {
      return isHealthy_;
    }
    /**
     * <code>bool isHealthy = 3;</code>
     */
    public Builder setIsHealthy(boolean value) {
      
      isHealthy_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool isHealthy = 3;</code>
     */
    public Builder clearIsHealthy() {
      
      isHealthy_ = false;
      onChanged();
      return this;
    }

    private int mapSize_ ;
    /**
     * <code>int32 mapSize = 4;</code>
     */
    public int getMapSize() {
      return mapSize_;
    }
    /**
     * <code>int32 mapSize = 4;</code>
     */
    public Builder setMapSize(int value) {
      
      mapSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 mapSize = 4;</code>
     */
    public Builder clearMapSize() {
      
      mapSize_ = 0;
      onChanged();
      return this;
    }

    private int responseCode_ ;
    /**
     * <code>int32 responseCode = 5;</code>
     */
    public int getResponseCode() {
      return responseCode_;
    }
    /**
     * <code>int32 responseCode = 5;</code>
     */
    public Builder setResponseCode(int value) {
      
      responseCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 responseCode = 5;</code>
     */
    public Builder clearResponseCode() {
      
      responseCode_ = 0;
      onChanged();
      return this;
    }

    private Object responseMessage_ = "";
    /**
     * <code>string responseMessage = 6;</code>
     */
    public String getResponseMessage() {
      Object ref = responseMessage_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        responseMessage_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string responseMessage = 6;</code>
     */
    public com.google.protobuf.ByteString
        getResponseMessageBytes() {
      Object ref = responseMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        responseMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string responseMessage = 6;</code>
     */
    public Builder setResponseMessage(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      responseMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string responseMessage = 6;</code>
     */
    public Builder clearResponseMessage() {
      
      responseMessage_ = getDefaultInstance().getResponseMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string responseMessage = 6;</code>
     */
    public Builder setResponseMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      responseMessage_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:NodeInfoResponse)
  }

  // @@protoc_insertion_point(class_scope:NodeInfoResponse)
  private static final NodeInfoResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new NodeInfoResponse();
  }

  public static NodeInfoResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NodeInfoResponse>
      PARSER = new com.google.protobuf.AbstractParser<NodeInfoResponse>() {
    @Override
    public NodeInfoResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NodeInfoResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NodeInfoResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<NodeInfoResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public NodeInfoResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

