// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: master.proto

package si.mlimedija.proto;

public interface NodeHandshakeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Master.NodeHandshakeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string nodeIpAddress = 1;</code>
   */
  java.lang.String getNodeIpAddress();
  /**
   * <code>string nodeIpAddress = 1;</code>
   */
  com.google.protobuf.ByteString
      getNodeIpAddressBytes();

  /**
   * <code>int32 nodePort = 2;</code>
   */
  int getNodePort();

  /**
   * <code>string nodeType = 3;</code>
   */
  java.lang.String getNodeType();
  /**
   * <code>string nodeType = 3;</code>
   */
  com.google.protobuf.ByteString
      getNodeTypeBytes();
}
