// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: master.proto

package si.mlimedija.proto;

public interface PutFileRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Master.PutFileRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes content = 1;</code>
   */
  com.google.protobuf.ByteString getContent();

  /**
   * <code>int32 chunkNumber = 2;</code>
   */
  int getChunkNumber();
}
