// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: master.proto

package si.mlimedija.proto;

public interface PutFileResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Master.PutFileResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 responseCode = 1;</code>
   */
  int getResponseCode();

  /**
   * <code>string responseMessage = 2;</code>
   */
  java.lang.String getResponseMessage();
  /**
   * <code>string responseMessage = 2;</code>
   */
  com.google.protobuf.ByteString
      getResponseMessageBytes();
}
