// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: master.proto

package si.mlimedija.proto;

/**
 * <pre>
 * initial response for put file
 * </pre>
 *
 * Protobuf type {@code Master.PutFileEndpointResponse}
 */
public  final class PutFileEndpointResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Master.PutFileEndpointResponse)
    PutFileEndpointResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PutFileEndpointResponse.newBuilder() to construct.
  private PutFileEndpointResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PutFileEndpointResponse() {
    nodeIpAddress_ = "";
    nodePort_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PutFileEndpointResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            nodeIpAddress_ = s;
            break;
          }
          case 16: {

            nodePort_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return si.mlimedija.proto.Master.internal_static_Master_PutFileEndpointResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return si.mlimedija.proto.Master.internal_static_Master_PutFileEndpointResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            si.mlimedija.proto.PutFileEndpointResponse.class, si.mlimedija.proto.PutFileEndpointResponse.Builder.class);
  }

  public static final int NODEIPADDRESS_FIELD_NUMBER = 1;
  private volatile java.lang.Object nodeIpAddress_;
  /**
   * <code>string nodeIpAddress = 1;</code>
   */
  public java.lang.String getNodeIpAddress() {
    java.lang.Object ref = nodeIpAddress_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nodeIpAddress_ = s;
      return s;
    }
  }
  /**
   * <code>string nodeIpAddress = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNodeIpAddressBytes() {
    java.lang.Object ref = nodeIpAddress_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nodeIpAddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NODEPORT_FIELD_NUMBER = 2;
  private int nodePort_;
  /**
   * <code>int32 nodePort = 2;</code>
   */
  public int getNodePort() {
    return nodePort_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNodeIpAddressBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nodeIpAddress_);
    }
    if (nodePort_ != 0) {
      output.writeInt32(2, nodePort_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNodeIpAddressBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nodeIpAddress_);
    }
    if (nodePort_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, nodePort_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof si.mlimedija.proto.PutFileEndpointResponse)) {
      return super.equals(obj);
    }
    si.mlimedija.proto.PutFileEndpointResponse other = (si.mlimedija.proto.PutFileEndpointResponse) obj;

    boolean result = true;
    result = result && getNodeIpAddress()
        .equals(other.getNodeIpAddress());
    result = result && (getNodePort()
        == other.getNodePort());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NODEIPADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getNodeIpAddress().hashCode();
    hash = (37 * hash) + NODEPORT_FIELD_NUMBER;
    hash = (53 * hash) + getNodePort();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static si.mlimedija.proto.PutFileEndpointResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static si.mlimedija.proto.PutFileEndpointResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static si.mlimedija.proto.PutFileEndpointResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static si.mlimedija.proto.PutFileEndpointResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static si.mlimedija.proto.PutFileEndpointResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static si.mlimedija.proto.PutFileEndpointResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static si.mlimedija.proto.PutFileEndpointResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static si.mlimedija.proto.PutFileEndpointResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static si.mlimedija.proto.PutFileEndpointResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static si.mlimedija.proto.PutFileEndpointResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static si.mlimedija.proto.PutFileEndpointResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static si.mlimedija.proto.PutFileEndpointResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(si.mlimedija.proto.PutFileEndpointResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * initial response for put file
   * </pre>
   *
   * Protobuf type {@code Master.PutFileEndpointResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Master.PutFileEndpointResponse)
      si.mlimedija.proto.PutFileEndpointResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return si.mlimedija.proto.Master.internal_static_Master_PutFileEndpointResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return si.mlimedija.proto.Master.internal_static_Master_PutFileEndpointResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              si.mlimedija.proto.PutFileEndpointResponse.class, si.mlimedija.proto.PutFileEndpointResponse.Builder.class);
    }

    // Construct using si.mlimedija.proto.PutFileEndpointResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      nodeIpAddress_ = "";

      nodePort_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return si.mlimedija.proto.Master.internal_static_Master_PutFileEndpointResponse_descriptor;
    }

    @java.lang.Override
    public si.mlimedija.proto.PutFileEndpointResponse getDefaultInstanceForType() {
      return si.mlimedija.proto.PutFileEndpointResponse.getDefaultInstance();
    }

    @java.lang.Override
    public si.mlimedija.proto.PutFileEndpointResponse build() {
      si.mlimedija.proto.PutFileEndpointResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public si.mlimedija.proto.PutFileEndpointResponse buildPartial() {
      si.mlimedija.proto.PutFileEndpointResponse result = new si.mlimedija.proto.PutFileEndpointResponse(this);
      result.nodeIpAddress_ = nodeIpAddress_;
      result.nodePort_ = nodePort_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof si.mlimedija.proto.PutFileEndpointResponse) {
        return mergeFrom((si.mlimedija.proto.PutFileEndpointResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(si.mlimedija.proto.PutFileEndpointResponse other) {
      if (other == si.mlimedija.proto.PutFileEndpointResponse.getDefaultInstance()) return this;
      if (!other.getNodeIpAddress().isEmpty()) {
        nodeIpAddress_ = other.nodeIpAddress_;
        onChanged();
      }
      if (other.getNodePort() != 0) {
        setNodePort(other.getNodePort());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      si.mlimedija.proto.PutFileEndpointResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (si.mlimedija.proto.PutFileEndpointResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object nodeIpAddress_ = "";
    /**
     * <code>string nodeIpAddress = 1;</code>
     */
    public java.lang.String getNodeIpAddress() {
      java.lang.Object ref = nodeIpAddress_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nodeIpAddress_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string nodeIpAddress = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNodeIpAddressBytes() {
      java.lang.Object ref = nodeIpAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeIpAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string nodeIpAddress = 1;</code>
     */
    public Builder setNodeIpAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nodeIpAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string nodeIpAddress = 1;</code>
     */
    public Builder clearNodeIpAddress() {
      
      nodeIpAddress_ = getDefaultInstance().getNodeIpAddress();
      onChanged();
      return this;
    }
    /**
     * <code>string nodeIpAddress = 1;</code>
     */
    public Builder setNodeIpAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nodeIpAddress_ = value;
      onChanged();
      return this;
    }

    private int nodePort_ ;
    /**
     * <code>int32 nodePort = 2;</code>
     */
    public int getNodePort() {
      return nodePort_;
    }
    /**
     * <code>int32 nodePort = 2;</code>
     */
    public Builder setNodePort(int value) {
      
      nodePort_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 nodePort = 2;</code>
     */
    public Builder clearNodePort() {
      
      nodePort_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Master.PutFileEndpointResponse)
  }

  // @@protoc_insertion_point(class_scope:Master.PutFileEndpointResponse)
  private static final si.mlimedija.proto.PutFileEndpointResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new si.mlimedija.proto.PutFileEndpointResponse();
  }

  public static si.mlimedija.proto.PutFileEndpointResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PutFileEndpointResponse>
      PARSER = new com.google.protobuf.AbstractParser<PutFileEndpointResponse>() {
    @java.lang.Override
    public PutFileEndpointResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PutFileEndpointResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PutFileEndpointResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PutFileEndpointResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public si.mlimedija.proto.PutFileEndpointResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

