// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: master.proto

package si.mlimedija.proto;

public interface PutKeysRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Master.PutKeysRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 nodeId = 1;</code>
   */
  int getNodeId();

  /**
   * <code>repeated string keys = 2;</code>
   */
  java.util.List<java.lang.String>
      getKeysList();
  /**
   * <code>repeated string keys = 2;</code>
   */
  int getKeysCount();
  /**
   * <code>repeated string keys = 2;</code>
   */
  java.lang.String getKeys(int index);
  /**
   * <code>repeated string keys = 2;</code>
   */
  com.google.protobuf.ByteString
      getKeysBytes(int index);
}
